### ISSUE TITLE
Nice work !!! When will the entire dataset available and the corresponding code with it? Is it already to use? 

### ISSUE THREAD

**Issue by yhw-yhw** [jutanke/hik#1]

**Comment by jutanke** [comment]
Thank you for your interest in our dataset. You can download a preliminary version here: https://drive.google.com/file/d/1ctMoU8PcBSUQtJWuLIPhomhEsh3Pg0bf/view

To load the dataset you can use our API as described here: https://github.com/jutanke/hik/blob/main/documentation/api.md

We are still ironing out some issues with the API which should be finalized for NeurIPS23, so ~Dec 10th 2023.
